books/urls.py
from django.urls import path
from books.views import IndexView, BookDetailView, GenreView, AddBookView, UpdateBookView, DeleteBookView

app_name = 'books'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('add/', AddBookView.as_view(), name='add'),
    path('<slug:slug>/update/', UpdateBookView.as_view(), name='update'),
    path('<slug:slug>/delete/', DeleteBookView.as_view(), name='delete'),

    path('g/<str:genre>/', GenreView.as_view(), name='genre'),
    path('<slug:slug>/', BookDetailView.as_view(), name='book-detail')
]

cbv/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls', namespace='website')),
    path('books/', include('books.urls', namespace='books')),
]

website/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import Ex2View
from . import views

app_name = 'website'
urlpatterns = [
    path('ex1', TemplateView.as_view(template_name='ex1.html', extra_context={'title': 'custom-title'})),
    path('ex2', Ex2View.as_view(), name='ex2'),
    
    
]

books/models.py
from turtle import title
from django.db import models
from django.template.defaultfilters import slugify


class Book(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(null=True)
    genre = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    isbn = models.IntegerField()
    count = models.IntegerField(null=True,default=0)


    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

events/models.py
from django.db import models

class Venue(models.Model):
    name = models.CharField('Venue Name', max_length=120)
    address = models.CharField(max_length=300)
    zip_code = models.CharField('Zip Code', max_length=120)
    phone = models.CharField('Contact Phone',max_length=25)
    web = models.URLField('Website Address')
    email_address = models.EmailField('Email Address')

    def __str__(self):
        return self.name

class MyClubUser(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField('User Email')



    def __str__(self):
        return self.first_name +' ' + self.last_name

class Event(models.Model):
    name = models.CharField('Event Name', max_length=120)
    event_date = models.DateTimeField('Event Date')
    venue = models.ForeignKey(Venue,blank=True, null=True, on_delete=models.CASCADE)
    manager = models.CharField(max_length=60)
    description = models.TextField(blank=True)
    attendees = models.ManyToManyField(MyClubUser, blank=True)

    def __str__(self):
        return self.name

runserver/models.py
from django.db import models

# Create your models here.

website/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)

books/forms.py
from django import forms
from .models import Book

class AddForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ('title', 'genre', 'author', 'isbn')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'genre':  forms.TextInput(attrs={'class': 'form-control'}),
            'author':  forms.TextInput(attrs={'class': 'form-control'}),
            'isbn': forms.TextInput(attrs={'class': 'form-control'}),

        }

books/views.py
from pyexpat import model
from django.shortcuts import render
# from django.views.generic.base  import TemplateView
from django.views.generic.detail  import DetailView
from django.views.generic.list  import ListView
from django.views.generic.edit import FormView,CreateView, UpdateView, DeleteView
from .models import Book
from django.db.models import F
from django.utils import timezone
from .forms import AddForm

class DeleteBookView(DeleteView):
    model = Book
    template_name = 'books/delete.html'
    context_object_name = 'book'
    
    success_url = '/books/'

class UpdateBookView(UpdateView):
    model = Book
    form_class = AddForm
    template_name = 'books/add.html'
    success_url = '/books/'


# class AddBookView(FormView):
#     template_name = 'add.html'
#     form_class = AddForm
#     success_url = '/books/'

#     def form_valid(self, form):
#         form.save()
#         return super().form_valid(form)


class AddBookView(CreateView):
    model = Book
    # fields = ['title', 'genre', 'author', 'isbn']
    form_class = AddForm
    template_name = 'books/add.html'
    success_url = '/books/'

    def get_initial(self, *args, **kwargs):
        initial = super().get_initial(**kwargs)
        initial['title'] = 'Enter Title'
        return initial

class IndexView(ListView):
    model = Book
    template_name = "books/home.html"
    # queryset = Book.objects.all()[:4]
    context_object_name = 'books'
    paginate_by = 4

    def get_queryset(self):
        return Book.objects.all()

class GenreView(ListView):
    model = Book
    template_name = "books/home.html"
    # queryset = Book.objects.all()[:4]
    context_object_name = 'books'
    # paginate_by = 2

    def get_queryset(self,*args, **kwargs):
        return Book.objects.filter(genre__icontains=self.kwargs.get('genre'))
    

    
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['books'] = Book.objects.all()
    #     return context

# class IndexView(TemplateView):
#     template_name = "home.html"
    
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['books'] = Book.objects.all()
#         return context


class BookDetailView(DetailView):
    model = Book
    template_name = 'books/book-detail.html'
    context_object_name = 'book'
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        post = Book.objects.filter(slug=self.kwargs.get('slug'))
        post.update(count=F('count') + 1)
        context['time'] = timezone.now()

        return context

events/views.py
from django.shortcuts import render

# Create your views here.

runserver/views.py
from django.shortcuts import render

# Create your views here.

website/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from .models import Post
from django.contrib.auth.models import AbstractBaseUser

# Create your views here.
class Ex2View(TemplateView):
    template_name = 'ex2.html'

    def get_context_data(self, **kwargs): 
        context =  super().get_context_data(**kwargs)
        context['posts'] = Post.objects.get(id=2)
        context['data'] = "Context Data for Ex2"
        return context

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <div class="container text-center">
        {% block content %}
        {% endblock content %}
        
    </div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/books/add.html
{% extends '../base.html' %}
{% block content %}
<div class="container shadow-lg mt-5" style="max-width: 600px;">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">All Books</h1>
        <p class="lead">A rnge of wonderfull programming books to help uou learn Javascript</p>
    </div>
    <div class="py-5">
        <div class="row">
            <div class="col-12">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p}}
                    <input type="submit">
                </form>
            </div>
        </div>
    </div>

</div>
{% endblock content %}

templates/books/book-detail.html
{% extends '../base.html' %}
{% block content %}

        <div class="row text-center my-5 border">
            <h1>Single Book</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium, et?</p>
        </div>
        <div class="row text-center my-5">
            <div class="row">
                
                <div class="col-md-6 mx-auto">
                    <a href="{% url 'books:index' %}" class="text-dark">
                        <div class="card mb-4 box-shadow shadow-sm border-1">
                            <div class="card-body">
                                <h2 style="font-size: 18px;font-weight:bold;min-height:42px;">{{book.title|truncatechars:50}}</h2>
                                <div class="d-flex justify-content-between align-items-center">
                                    <small class="text-muted border">{{book.genre}}</small>
                                    <small class="text-muted">{{book.author}}</small>

                                    <small class="text-muted">{{book.isbn}}</small>
                                    <small class="text-muted">{{time}}</small>
                                </div>
                                <div class="my-4">
                                    <a href="{% url 'books:update' slug=book.slug %}" class="btn btn-outline-primary me-3">Update</a>
                                    <a href="{% url 'books:delete' slug=book.slug %}" class="btn btn-outline-danger">Delete</a>
                                </div>
                                
                            </div>
                        </div>
                    </a>
                   
                  </div>
               
               
        </div>
        
    {% endblock content %}

templates/books/delete.html
{% extends '../base.html' %}
{% block content %}
<div class="container shadow-lg mt-5" style="max-width: 600px;">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Confirm Deletion</h1>
        
    </div>
    <div class="py-5">
        <div class="row">
            <div class="col-12">
                <form method="post">
                    {% csrf_token %}
                    <h1>Do you want to delete the book "{{book.title}}"?</h1>
                    <p>
                        <input type="submit" value="Yes"> 
                        <a href="{% url 'books:book-detail' slug=book.slug %}">Cancel</a>
                    </p>
                    
                </form>
            </div>
        </div>
    </div>

</div>
{% endblock content %}

templates/books/home.html
{% extends '../base.html' %}
{% block content %}

        <div class="row text-center my-5 border">
            <h1>All Books</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium, et?</p>
        </div>
        <div class="row text-center my-5">
            <div class="row">
                {% for book in books %}
                <div class="col-md-4 ">
                    
                        <div class="card mb-4 box-shadow shadow-sm">
                            <div class="card-body">
                                <a href="{% url 'books:book-detail' slug=book.slug %}" class="text-dark">
                                <h2 style="font-size: 18px;font-weight:bold;min-height:42px;">{{book.title|truncatechars:50}}</h2>
                                </a>
                                <div class="d-flex justify-content-between align-items-center">
                                    <a href="{% url 'books:genre' genre=book.genre %}" class="text-dark">
                                        <small class="text-muted">{{book.genre}}</small>
                                    </a>
                                    
                                    
                                    <small class="text-muted">{{book.isbn}}</small>
                                    <a href="{% url 'books:index' %}" class="text-dark">
                                        <small class="text-muted">All Books</small>
                                    </a>
                                    
                                </div>
                            </div>
                        </div>
                    
                   
                  </div>
                {% endfor %}
        </div>
        <div class="row">
            <div class="col-12  bg-light border">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{page_obj.previous_page_number}}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
                    </span>

                    {% if page_obj.has_next %}
                    <a href="?page={{page_obj.next_page_number}}">next</a>
                    <a href="?page={{page_obj.paginator.num_pages}}">last &raquo;</a>
                    {% endif %}

                </span>
            </div>
        </div>
        
    {% endblock content %}